algoritmo "semnome"
var
  a , b , c: real
inicio
  a := (4/2) + (2/4)
  escreva (a , " =")
  a:=  4/2+2/4
   escreval (a)
   escreval ("a1 e a2 são iguais")
   escreval ("")

   b:= 4/(2+2)/4
   escreva (b , " =")
   b:= 4/2+2/4
   escreval(b)
   escreval ("b1 e b2 não são iguais")
   escreval ("")
   
   c:=(4+2)*2-4
   escreva (c," =")
   c:= 4+2*2-4
   escreval (c)
   escreval ("c1 e c2 nao sao iguais")
   escreval ("")
   
fimalgoritmo

